# configuration file for the stocky server program. This is a YAML file defining
# a single dictionary
#
# configuration file version
VERSION: 1.0
#
#- the linux device name over which communication with the RFID reader takes place.
# when connected by USB, this is usually something like '/dev/ttyUSB0'
# when connected by Bluetooth, this is usually something like '/dev/rfcomm0'
RFID_READER_DEVNAME: '/dev/rfcomm0'

#-- The URL of the QAI server from where stocky gets the current stock status
QAI_URL: "http://192.168.69.170:4567"

# The QAI stock status is stored to a local file in the state directory with this name
LOCAL_STOCK_DB_FILE: 'localstock.sqlite'

#-----
# The region mode of the RFID reader. This defines the operation frequency and power output
# of the reader. This must be a valid entry according to the TLS ASCII protocol, command ".sr" .
RFID_REGION_CODE: 'us'
# --
# The time zone that should be used in reporting times.
# This must be a string known to the pytz module 'print(pytz.all_timezones)'
# NOTE: set this variable to a question mark and run the server to get a list of all
# known time zones.
#TIME_ZONE: '?'
TIME_ZONE: 'America/Vancouver'

