@startuml

skinparam defaultFontName Courier

Class Location {
    INTEGER ★ id  
    VARCHAR ⚪ name
}

Class Locmutation {
    INTEGER   ★ reag_item_id
    TIMESTAMP ⚪ created_at  
    BOOLEAN   ⚪ ignore      
    INTEGER   ⚪ locid       
    VARCHAR   ⚪ op          
}

Class Reagent {
    INTEGER ★ id                 
    VARCHAR ⚪ basetype           
    VARCHAR ⚪ catalog_number     
    VARCHAR ⚪ category           
    VARCHAR ⚪ date_msds_expires  
    VARCHAR ⚪ disposed           
    INTEGER ⚪ expiry_time        
    VARCHAR ⚪ hazards            
    VARCHAR ⚪ msds_filename      
    VARCHAR ⚪ name               
    VARCHAR ⚪ needs_validation   
    VARCHAR ⚪ notes              
    INTEGER ⚪ qcs_document_id    
    VARCHAR ⚪ storage            
    INTEGER ⚪ supplier_company_id
}

Class Reagent_Item {
    INTEGER ★ id             
    VARCHAR ⚪ last_seen      
    VARCHAR ⚪ lot_num        
    VARCHAR ⚪ notes          
    INTEGER ⚪ qcs_location_id
    INTEGER ⚪ qcs_reag_id    
    VARCHAR ⚪ rfid           
}

Class Reagent_Item_Composition {
    INTEGER ★ id         
    INTEGER ⚪ src_item_id
    INTEGER ⚪ sub_item_id
}

Class Reagent_Item_Status {
    INTEGER ★ id               
    VARCHAR ⚪ occurred         
    INTEGER ⚪ qcs_reag_item_id 
    INTEGER ⚪ qcs_user_id      
    INTEGER ⚪ qcs_validation_id
    VARCHAR ⚪ status           
}

Class TableChange {
    VARCHAR ★ table_name
    VARCHAR ⚪ stamp     
}

Class TimeUpdate {
    INTEGER   ★ id
    TIMESTAMP ⚪ dt
}

Class User {
    INTEGER ★ id      
    VARCHAR ⚪ email   
    VARCHAR ⚪ initials
    VARCHAR ⚪ login   
}

right footer generated by sadisplay v0.4.9

@enduml