

OPTS = -dc -ds -n -b -e6



typingtest01: __target__/typingtest01.js ## compile the web client (from python to javascript)

__target__/typingtest01.js: Makefile typingtest01.py
	transcrypt ${OPTS} typingtest01




