@startuml
title classes stockyserver
class BaseServer {
    +logger
    +msgQ
    +name
    +websocketTM
    +ws
    +en_queue(self, msg:CommonMSG)
    +mainloop(self)
    +send_ws_msg(self, msg:CommonMSG)
    +set_websocket(self, newws:ServerWebSocket.BaseWebSocket)
    +sleep(self, secs:int)
}
class CommonStockyServer {
    +MSG_FOR_ME_SET
    +MSG_FOR_RFID_SET
    +MSG_FOR_WC_SET
    +cfg_dct
    +comm_link
    +filewatcher
    +qaisession
    +rfcommtask
    +rfid_delay_task
    +stockdb
    +timer_tm
    +tls
    +ws
    +activate_rfid_spinner(self)
    +bt_init_reader(self)
    +handle_rfid_clstatechange(self, new_state:int)
    +handle_rfid_filestatechange(self, file_is_made:bool)
    +mainloop(self)
    +send_qai_status(self, upd_dct:typing.Optional[dict])
    +send_server_config(self)
    +server_handle_msg(self, msg:CommonMSG)
}
class StockyDBServer 
class StockyRFIDServer 
class RfidPingServer {
    +SEC_INTERVAL_SECS
    +scan_generator
    +ws
    +mainloop(self)
}

BaseServer <|-- CommonStockyServer
CommonStockyServer <|-- StockyDBServer
CommonStockyServer <|-- StockyRFIDServer
BaseServer <|-- RfidPingServer

@enduml
