@startuml
title classes commlink
class CLResponse {
    +rl
    +get_comment_dct(self)
    +return_code(self)
}
class BaseCommLink {
    +COMMENT_ID
    +DCT_START_CHAR
    +DCT_STOP_CHAR
    +MSGNUM_ID
    +RC_FAULTY
    +RC_NO_BARCODE
    +RC_NO_TAGS
    +RC_OK
    +RC_TIMEOUT
    +cfgdct
    +logger
    +mydev
    +rfid_info_dct
    +encode_comment_dict(d:dict)
    +extract_comment_dict(s:str)
    +get_info_dct(self)
    +get_rfid_state(self)
    +handle_state_change(self, is_online:bool)
    +id_string(self)
    +is_alive(self)
    +open_device(self)
    +raw_read_response(self)
    +raw_send_cmd(self, cmdstr:str)
    +rc_string(ret_code:TLSRetCode)
    +send_cmd(self, cmdstr:str, comment:str=None)
}
class SerialCommLink {
    +rfid_info_dct
    +id_string(self)
    +open_device(self)
}

BaseCommLink <|-- SerialCommLink

@enduml
