@startuml
component [wccontroller] as wccontroller
component [wcviews] as wcviews
component [wcstatus] as wcstatus
component [webclient] as webclient
component [commonmsg] as commonmsg
package "org" {
package "transcrypt" {
package "stubs" {
interface browser as org.transcrypt.stubs.browser #Yellow
}
}
}
interface typing as typing #Yellow
package "qailib" {
package "transcryptlib" {
interface forms as qailib.transcryptlib.forms #Yellow
interface genutils as qailib.transcryptlib.genutils #Yellow
interface htmlelements as qailib.transcryptlib.htmlelements #Yellow
interface widgets as qailib.transcryptlib.widgets #Yellow
interface simpletable as qailib.transcryptlib.simpletable #Yellow
interface cleverlabels as qailib.transcryptlib.cleverlabels #Yellow
interface SVGlib as qailib.transcryptlib.SVGlib #Yellow
interface websocket as qailib.transcryptlib.websocket #Yellow
interface serversocket as qailib.transcryptlib.serversocket #Yellow
}
package "common" {
interface base as qailib.common.base #Yellow
interface serversocketbase as qailib.common.serversocketbase #Yellow
}
}
[qailib.transcryptlib.forms] --> [wcstatus]
[typing] --> [wcstatus]
[qailib.transcryptlib.genutils] --> [wcstatus]
[qailib.transcryptlib.htmlelements] --> [wcstatus]
[qailib.transcryptlib.widgets] --> [wcstatus]
[webclient.commonmsg] --> [wcstatus]
[qailib.transcryptlib.simpletable] --> [wcstatus]
[qailib.common.base] --> [wcstatus]
[qailib.transcryptlib.websocket] --> [webclient]
[org.transcrypt.stubs.browser] --> [webclient]
[qailib.transcryptlib.genutils] --> [webclient]
[qailib.transcryptlib.serversocket] --> [webclient]
[webclient.wccontroller] --> [webclient]
[org.transcrypt.stubs.browser] --> [wcviews]
[typing] --> [wcviews]
[qailib.transcryptlib.htmlelements] --> [wcviews]
[qailib.transcryptlib.cleverlabels] --> [wcviews]
[qailib.transcryptlib.SVGlib] --> [wcviews]
[qailib.transcryptlib.widgets] --> [wcviews]
[webclient.commonmsg] --> [wcviews]
[qailib.transcryptlib.simpletable] --> [wcviews]
[webclient.wcstatus] --> [wcviews]
[qailib.common.base] --> [wcviews]
[typing] --> [commonmsg]
[qailib.transcryptlib.forms] --> [wccontroller]
[typing] --> [wccontroller]
[qailib.transcryptlib.genutils] --> [wccontroller]
[qailib.transcryptlib.htmlelements] --> [wccontroller]
[qailib.transcryptlib.widgets] --> [wccontroller]
[webclient.commonmsg] --> [wccontroller]
[webclient.wcviews] --> [wccontroller]
[webclient.wcstatus] --> [wccontroller]
[qailib.common.base] --> [wccontroller]
[qailib.common.serversocketbase] --> [wccontroller]
wcstatus -[hidden]- qailib
wcstatus -[hidden]- webclient
wcstatus -[hidden]- wcviews
wcstatus -[hidden]- org
wcstatus -[hidden]- commonmsg
wcstatus -[hidden]- wccontroller
qailib -[hidden]- webclient
qailib -[hidden]- wcviews
qailib -[hidden]- org
qailib -[hidden]- commonmsg
qailib -[hidden]- wccontroller
webclient -[hidden]- wcviews
webclient -[hidden]- org
webclient -[hidden]- commonmsg
webclient -[hidden]- wccontroller
wcviews -[hidden]- org
wcviews -[hidden]- commonmsg
wcviews -[hidden]- wccontroller
org -[hidden]- commonmsg
org -[hidden]- wccontroller
commonmsg -[hidden]- wccontroller
@enduml
